spring:
  main:
    web-application-type: reactive
  application:
    name: reactive
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,
              org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
              org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/test